---
- name: Install/Upgrade Hashicorp Vault
  hosts: all
  gather_facts: yes
  become: True
  collections:
    - nixknight.general
    - nixknight.docker
  vars_files:
  - "{{ playbook_dir }}/extravars/acme.yml"
  roles:
    - linux-common
    - motd
    - acme
    - role: docker-compose-service
      DOCKER_COMPOSE_SERVICE_NAME: "{{ HASHI_VAULT_SERVICE_NAME }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_DESCRIPTION: "{{ HASHI_VAULT_SERVICE_SYSTEMD_DESCRIPTION }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_REQUIRES: "{{ HASHI_VAULT_SERVICE_SYSTEMD_REQUIRES }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_AFTER: "{{ HASHI_VAULT_SERVICE_SYSTEMD_AFTER }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_FILE: "{{ HASHI_VAULT_SERVICE_SYSTEMD_FILE }}"
      DOCKER_COMPOSE_SERVICE_IMAGES: "{{ HASHI_VAULT_SERVICE_IMAGES }}"
      DOCKER_COMPOSE_SERVICE_COMPOSE_PATH: "{{ HASHI_VAULT_SERVICE_COMPOSE_PATH }}"
      DOCKER_COMPOSE_SERVICE_CONFIG_PATH: "{{ HASHI_VAULT_COMPOSE_SERVICE_CONFIG_PATH }}"
      DOCKER_COMPOSE_SERVICE_FILES: "{{ HASHI_VAULT_COMPOSE_SERVICE_FILES}}"
      DOCKER_COMPOSE_SERVICE_MANIFEST: "{{ HASHI_VAULT_SERVICE_MANIFEST }}"
